version: '3'

services:
  pluto_web:
    image: node:12.16.2-alpine # 指定服务镜像
    tty: true
    container_name: pluto_web # 容器名称
    working_dir: /home/plutoweb/client/public
    environment:
      - HOST=0.0.0.0
    ports:
      - '80:3000'
    volumes:
      - /home/plutoweb/client/public:/home/plutoweb/client/public
    command: sh -c "npm install --production --registry=https://registry.npm.taobao.org && npm start"