version: '3'

services:
  pluto_client:
    build: # 这里指的是我们刚刚撸的 Dockerfile 文件
      context: .
      dockerfile: Dockerfile
    image: node:12.16.2-alpine # 镜像名称
    container_name: pluto_client # 容器名称
    restart: always # 重启方式
